Fixed: String cannot be converted to Packaging
Fixed and error which caused compilation failure due to a type mismatch.
ReleaseIndex.java:[486,33] error: incompatible types: String cannot be converted to Packaging
The expected argument to release.setPackaging() method is an instance of Packaging, but a string was being passed.